# Generated by Django 3.2.12 on 2022-04-19 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('issue_a', models.CharField(max_length=20)),
                ('issue_b', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('pick', models.CharField(max_length=20)),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eithers.question')),
            ],
        ),
    ]
